// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRo_23BH4todbWBac4j1yj6e3pk6iSnbU',
    appId: '1:782620094559:web:bea22d5f611887f47cabea',
    messagingSenderId: '782620094559',
    projectId: 'socialmediaapp-8697c',
    authDomain: 'socialmediaapp-8697c.firebaseapp.com',
    storageBucket: 'socialmediaapp-8697c.firebasestorage.app',
    measurementId: 'G-YDKFLV8ZZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANF3IWnj8pGR89hG2iisFaU_2GnCcMyPE',
    appId: '1:782620094559:android:933775e90a49832e7cabea',
    messagingSenderId: '782620094559',
    projectId: 'socialmediaapp-8697c',
    storageBucket: 'socialmediaapp-8697c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt7reoxShg2w4A50bYZklHDO8-EyTD5bc',
    appId: '1:782620094559:ios:21c32b89b5724bf17cabea',
    messagingSenderId: '782620094559',
    projectId: 'socialmediaapp-8697c',
    storageBucket: 'socialmediaapp-8697c.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
